[package]
   name = "hashpp"
   version = "0.0.1"
   description = "c++ hash algorithm library"
   git = "https://github.com/injae/hashpp.git"

[[lib]]
   name = "hashpp"
   type = "static"
   source = ["src/.*"]
